### ISSUE TITLE
example in README 

### ISSUE THREAD

**Issue by Dowwie** [japaric/criterion.rs#116]
Is this expected when running the example in the repo's README.md?

Benchmarking fib 20: Collecting 100 samples in estimated 5.0000 s (20506333000 iterations)

**Comment by bheisler** [comment]
That looks pretty typical, yes. Criterion.rs runs many iterations per sample in order to reach the target measurement time. With a fast function and/or a fast computer that can result in comically large iteration counts.

In this case, that's probably an indication that the measurement time should be turned down for that benchmark, but it's not an error.
