### ISSUE TITLE
Is the Display constraint on input necessary

### ISSUE THREAD

**Issue by b52** [japaric/criterion.rs#118]
I just wanted to perform two functions using `Criterion::bench_functions()`, but the constraint on the `input` to implement `Display` made me stop. Is this a necessary constraint? If so, why? Is it reasonable to lift it to `Debug`, which can be derived automatically in contrast to `Display`.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.

The Display constraint is used to convert the input to string for display and file names and the like. Changing it to accept Debug instead would be reasonable I think - as you say, it's `#[derive]`-able and we probably don't need to be too concerned about the difference between developer- and user-facing output since this is a development tool.

This would be a SemVer breaking change though, so it will have to wait for 0.2.

**Comment by dvdplm** [comment]
For posterity, I ran into this trying to pass in a `Vec<isize>` and got at `error[E0277]: the trait bound `std::vec::Vec<isize>: std::fmt::Display` is not satisfied`. Thanks for the fix! :)
