### ISSUE TITLE
Multiple groups

### ISSUE THREAD

**Issue by llogiq** [japaric/criterion.rs#122]
While checking out criterion (see the `criterion` branch at [bytecount](https://github.com/llogiq/bytecount)), I found that the `criterion_main!` macro doesn't accept multiple groups.

**Comment by bheisler** [comment]
It seems to be working [here](https://github.com/japaric/criterion.rs/blob/master/benches/bench_main.rs).

I took a look at your code; I think the problem is that you're reusing the names `count` and `num_chars`. If I change it to the following it compiles just fine:
```rust
   criterion_group!(count_benches, bench_naive_count, bench_naive_count_32,
                 bench_count);
   criterion_group!(num_chars_benches, bench_naive_num_chars, bench_num_chars);
   criterion_main!(count_benches, num_chars_benches);
```

The compile error is really misleading there, though. I'm not sure if there's anything I can do with macros-by-example to give better error messages, unfortunately.

Hope this helps!

**Comment by llogiq** [comment]
Ah, I see. Perhaps document this problem so people will know where to look?
