### ISSUE TITLE
Csv Report

### ISSUE THREAD

**Issue by nickbabcock** [japaric/criterion.rs#147]
While the criterion html report is decent for most situations, there are occasions when a different graph allows for an easier interpretation. Instead making the html report endlessly configurable, I propose exposing the data in a csv format. This way, anyone can easily create their graph in R, python, etc. While the json in `target/criterion/$BENCHMARK/$FUNCTION` is a good start -- pulling everything together into a (preferably) single file would greatly lower the bar.

For instance a `$cargobenchname-raw.csv` could hold the raw sampling data with headers like:

| group id | id | parameter | elapsed (ns) |
| -------- | -- | --------- | ------------ |
| a           | b  |                | 100             |
| a           | b  |                | 150             |

Where group id and parameter can be left blank for the benchmarks that don't apply. I'm torn if throughput should be included. I'm leaning towards no, as I believe it's calculable. Users of the raw data can calculate additional aggregations they are interested in (like percentiles)

Alternatively (or in addition), the aggregated values can be written to `$cargobenchname.csv` 

| group id | id | parameter | elapsed (ns) | x̅ | x̅ p95 upper | x̅ p95 lower | σ<sub>x̅<sub> |
| -------- | -- | --------- | ------------ | - | ----------- | ----------- | -- |

More than just the mean statistics would be included.

As a comparison, the [C# BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) outputs a [csv like this](https://github.com/nickbabcock/Farmhash.Sharp/blob/20888cde1692f89d2bae059034471ea85e15593a/benchmarks.csv), which can be slurped up to [create nice looking graphs](https://nickbabcock.github.io/Pfim/img/benchmark.png).

Maybe this could help people transition to presenting rust benchmark results in graphical form. I know that my Rust projects don't get enough love in the dataviz department 😄

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and sorry for the slow response.

There have been requests for a stable machine-readable output format (eg. for [lolbench](https://github.com/anp/lolbench)). The current JSON storage format is an internal implementation detail. I was leaning more towards defining a stable JSON interchange format that could be different from the storage format, rather than CSV, but I could be convinced otherwise. Why did you choose to go with CSV over JSON?

That said, I don't agree that a single large file is the way to go, for a lot of reasons. The most important one is that it's actually really difficult to have a complete list of the benchmarks for a given repository - some benchmarks might have been filtered out, some might be run with a different instance of the Criterion struct, some might be in a totally different binary. The HTML report works around this to generate the index by walking the directory tree, which is kind of an ugly hack and often involves overwriting the file multiple times. I'd prefer not to repeat that hack if possible. I don't see the need for combining all of the output into a single file anyway; anyone who is writing a script to parse these files can surely handle reading multiple files.

Also if Criterion.rs does add something like this, the output format should include the number of iterations in each sample. That will be necessary for the consumer to calculate summary statistics correctly.

It's not a bad idea, but I think it needs some more work.

**Comment by bheisler** [comment]
I'm sorry, I wasn't clear earlier. What you're proposing is much harder to accomplish than you realize, but it's not immediately obvious why that's the case so I'll try to explain.

Where do you propose to store the results before writing them to the CSV file, and how do you decide when to overwrite (as opposed to appending to) that file?

If we store them in the Criterion struct, we run into the problem that the Criterion struct gets discarded after every benchmark group. You could write to disk at the end of the benchmark (as your current implementation does) but then each benchmark will overwrite the last. You can get around that by storing the results in some sort of global static storage. However, Cargo makes it easy to define multiple benchmark executables - what you refer to as `bencha` and `benchb`. It's fairly common for Criterion.rs users to do this, so your solution has to be able to handle that usage pattern. If you naively write your CSV file at the end of `main`, then the last executable to run will win, which is also not what you want.

As far as I'm aware, Cargo doesn't provide any way to know which executable we're in or what other executables there are or what benchmarks might be in them, so you can't even write to different files. I don't think you can even look at the executable path in `argv[0]` because Cargo mangles the names of the benchmark executables and they change every so often.

You could append to the file instead of overwriting it, but now you have a different problem - you can't tell if the existing results file was written by a previous executable in the same `cargo bench` invocation, or if it was written by an earlier benchmarking run (potentially benchmarking a different version of the code). Now your CSV file grows unbounded and probably contains wrong data as well.

The problem here is that we don't have any good way to determine a complete list of which benchmarks were run in a given `cargo bench` run - there might be filters or there might be more benchmark executables waiting in Cargo's queue. We also don't have any way to run code at the start or end of a `cargo bench` run (eg. to clear the CSV file at the start of a run).

As I said before, the way I work around this to generate the HTML report index is to walk the file tree to scan for stored benchmark files, but this is unsatisfactory too. It's expensive - a full directory traversal. It's wasteful - all benchmark executables will perform this traversal and write a file, only to have it overwritten by the next executable. And it's not even all that accurate - if I delete a benchmark from my code and run `cargo bench` again, it still shows up in the index because the stored results files are still there. In your case, there's even more potential to confuse users. If a user changes their code and then runs a subset of the benchmarks (using the `--bench` argument to pick a single executable or just providing a filter) then the directory scan will pick up all the other results files from benchmarks that weren't executed and may no longer be accurate.

It's probably not possible to correctly handle all of these corner cases without some kind of support from Cargo. Although I suppose you could get close, it would involve a lot of guesswork and complexity on Criterion's part and I don't want that maintenance burden.

If you're feeling particularly ambitious, you could try to convince the developers of Cargo to set environment variables when running the benchmark executables. For example, you could tell Criterion 'this is executable 1 of 3' and then Criterion could clear the CSV file. But even there you run into corner cases - what if some of the benchmark executables don't use Criterion? If the first executable uses Bencher or something instead, then you'll never clear the CSV file.

Or you could just write a separate CSV file for every benchmarked function. That's easy to do and there's no problem with different benchmarks or different executables interfering with each other. True, the user now has to do `find | cat | grep | analysis.py` or something like that to do their analysis. It's more work, sure, but it's explicit about the directory scan so there's less potential for confusion in odd corner cases and the user knows exactly what they're analyzing. We could make this easier by including the benchmark ID information (in separate columns to avoid ambiguity), even though it's technically redundant with the file path.

I hope this rant explains some of my thinking on this issue. I've already made all of these mistakes while trying to implement the HTML report index, you see, and it was not so much fun that I want to do it again.

> I don't want to decipher new/sample.json.

Well, that's not really intended to be a user-facing format. In fact, it could change without warning (and already has at least once) so it's probably not a good idea to rely on it too heavily.

I'd also like to think some more about what should be in this hypothetical CSV file. Is it more useful to have the raw samples, or would you want to read the summary statistics instead? It's tempting to say that Criterion should save both, but that means more code to maintain. I'm kind of inclined to only expose the raw sample data to keep the API surface as minimal as possible, but then users have to compute their own summary statistics. I don't want to inflict work on users without good reason, but I also don't want to have to support something that nobody uses.

**Comment by nickbabcock** [comment]
Ah thanks for the patience! It appears that we're blocked on Cargo before we can even begin to talk specifics. I'm feeling strangely motivated to make this possible, so I'll look to open a pre-rfc thread on internals in the next couple days and see what others think. There may be a solution that custom test harnesses could use too 🤔 

> I'm kind of inclined to only expose the raw sample data to keep the API surface as minimal as possible

That would be fine with me.

> then users have to compute their own summary statistics

True, but if / when that is too much work, people will open an issue with suggestions, so you'll know what's important to others and that others are using the feature.

**Comment by nickbabcock** [comment]
So I've updated the PR so that criterion takes advantage of [`module_path!`](https://doc.rust-lang.org/nightly/std/macro.module_path.html) This avoids clobbering, so that benchmarks under `bencha.rs` end up under `bencha-raw.csv` and `benchb.rs` ends up under `benchb-raw.csv`, so it is possible to consolidate all benchmarks in one benchmark executable into a single output file. I've tested it for my own use cases and it works.

Was `module_path` what you were looking for to fix the cargo blocker? If so, we can move onto what your thoughts are on defining an output that most can agree on. No need to review the PR (again!) until we settle up here, I'm just using it as a reference for discussion.

**Comment by bheisler** [comment]
Well, the issue there is that `module_path!` resolves to... well, the module path. If the user has their criterion group inside a module, and many will, that will produce a file name like "test::foo-raw.csv". Windows, at least, doesn't like to have `:` in file names.

**Comment by nickbabcock** [comment]
Yes, colons can be replaced with a permissible character (like a dash) or take everything after the last colon

**Comment by Mart-Bogdan** [comment]
Hello, I would like this issue to be reopened.

current implementation isn't very useful. 

```csv
group,function,value,throughput_num,throughput_type,sample_measured_value,unit,iteration_count
Array2DGameGrid,Classic,       1,,,1014529.0,ns,23
Array2DGameGrid,Classic,       1,,,2019670.0,ns,46
Array2DGameGrid,Classic,       1,,,3015303.0,ns,69
Array2DGameGrid,Classic,       1,,,4017668.0,ns,92
Array2DGameGrid,Classic,       1,,,5131014.0,ns,115
```

I guess I would be able to something with it using R, if I know it.

But what was described in this isse is simple format with already calculated mean value, so user won't be required to calcualte mean and stdev by them-self, as criterion already calculates this in console output. 

Something like this:
![image](https://github.com/bheisler/criterion.rs/assets/775038/a71f68b1-551e-4da1-b9db-ac97e4ef13e3)

So It would be useful to draw charts in Excel.

I also want to compare performance of same code with dotnet.
Dotnet's benchmark CSV is provided in link it issue.

My screenshot is same csv with non important columns removed. "Iterations" is name of parameter, for our purpsoes it can be just Parmater  (for `g.bench_with_input`).

Well we can just print benchmark ID + Benchmark Group and leave with it.

Currently I'm doing this to have distinguishable names:
```rs
g.bench_with_input(
    BenchmarkId::new("Classic", format!("{:>8}", size)),
    &size,
    |b, s| b.iter(|| {
        let res = game.into_iter().take(*s).last();
        black_box(res)
    }),
);
```

I also would prefer for generated CSV to be in same measurement scale, for example everything in  µs, but having separate column with unit (as it is with current raw csv) would also work. 

P.S. also BenchmarkDotnet prints summary table to console, but that would be  issue
<details>
  <summary>Output of Becnhmark.NET</summary>
it prints following output, actually already in markdown:

```
|   Method | Iterations |         Mean |      Error |     StdDev |     Gen 0 | Gen 1 | Gen 2 |   Allocated |
|--------- |----------- |-------------:|-----------:|-----------:|----------:|------:|------:|------------:|
|  Classic |          1 |     96.71 us |   0.814 us |   0.722 us |         - |     - |     - |    46.84 KB |
| Parallel |          1 |     55.03 us |   1.998 us |   5.699 us |         - |     - |     - |    56.05 KB |
|  Classic |         10 |    947.12 us |  15.878 us |  13.259 us |         - |     - |     - |   464.91 KB |
| Parallel |         10 |    304.37 us |   8.433 us |  23.648 us |         - |     - |     - |    557.1 KB |
|  Classic |         50 |  4,795.82 us |  37.975 us |  35.522 us |         - |     - |     - |  2323.04 KB |
| Parallel |         50 |  1,428.32 us |  34.468 us |  99.448 us |         - |     - |     - |  2783.98 KB |
|  Classic |        100 |  7,326.27 us |  30.579 us |  49.379 us |         - |     - |     - |   4645.7 KB |
| Parallel |        100 |  2,882.55 us |  89.709 us | 263.101 us |         - |     - |     - |  5567.63 KB |
|  Classic |        200 | 15,871.85 us | 125.254 us | 117.162 us | 1000.0000 |     - |     - |  9291.01 KB |
| Parallel |        200 |  5,858.96 us | 158.779 us | 465.672 us | 1000.0000 |     - |     - | 11134.88 KB |
|  Classic |        500 | 39,657.94 us | 214.375 us | 190.038 us | 2000.0000 |     - |     - | 23226.95 KB |
| Parallel |        500 | 13,324.36 us | 248.732 us | 571.504 us | 3000.0000 |     - |     - | 27836.79 KB |
```

|   Method | Iterations |         Mean |      Error |     StdDev |     Gen 0 | Gen 1 | Gen 2 |   Allocated |
|--------- |----------- |-------------:|-----------:|-----------:|----------:|------:|------:|------------:|
|  Classic |          1 |     96.71 us |   0.814 us |   0.722 us |         - |     - |     - |    46.84 KB |
| Parallel |          1 |     55.03 us |   1.998 us |   5.699 us |         - |     - |     - |    56.05 KB |
|  Classic |         10 |    947.12 us |  15.878 us |  13.259 us |         - |     - |     - |   464.91 KB |
| Parallel |         10 |    304.37 us |   8.433 us |  23.648 us |         - |     - |     - |    557.1 KB |
|  Classic |         50 |  4,795.82 us |  37.975 us |  35.522 us |         - |     - |     - |  2323.04 KB |
| Parallel |         50 |  1,428.32 us |  34.468 us |  99.448 us |         - |     - |     - |  2783.98 KB |
|  Classic |        100 |  7,326.27 us |  30.579 us |  49.379 us |         - |     - |     - |   4645.7 KB |
| Parallel |        100 |  2,882.55 us |  89.709 us | 263.101 us |         - |     - |     - |  5567.63 KB |
|  Classic |        200 | 15,871.85 us | 125.254 us | 117.162 us | 1000.0000 |     - |     - |  9291.01 KB |
| Parallel |        200 |  5,858.96 us | 158.779 us | 465.672 us | 1000.0000 |     - |     - | 11134.88 KB |
|  Classic |        500 | 39,657.94 us | 214.375 us | 190.038 us | 2000.0000 |     - |     - | 23226.95 KB |
| Parallel |        500 | 13,324.36 us | 248.732 us | 571.504 us | 3000.0000 |     - |     - | 27836.79 KB |

</details>
