### ISSUE TITLE
Better support for testing benchmarks

### ISSUE THREAD

**Issue by bheisler** [japaric/criterion.rs#162]
[This Reddit thread](https://www.reddit.com/r/rust/comments/8uj5oa/criterion_benchmark_with_onetime_setup_also_how/) points out that it would be useful to have a way to execute the benchmarks just once, in order to verify that they're being run successfully.

Criterion.rs could perhaps support this pattern better, or at least if Cargo gives an easy way for us to distinguish between `cargo bench` and `cargo test --bench`.

**Comment by KillTheMule** [comment]
So, in going for a compromise as you suggested I was bitten by [this assertion](https://github.com/japaric/criterion.rs/blob/master/stats/src/univariate/sample.rs#L43). Could we simply allow length 1 here? If not, the documentation should be changed, since it only mentions disallowing length 0 for `sample_size`.

I'd send a PR, just let me know what to do about this.
