### ISSUE TITLE
label parameters of parameterized benchmarks

### ISSUE THREAD

**Issue by mykmelez** [japaric/criterion.rs#178]
In [mykmelez/kvbench](https://github.com/mykmelez/kvbench/), I recently used Criterion.rs to benchmark two key/value storage engines, and I parameterized the benchmarks by the number of key/value pairs and the size of values. When I showed an example benchmark run to a colleague, his first question was what the parenthesized numbers in the benchmark names represent, as they aren't labeled or otherwise identified.

For example, on the command line, one of the parameterized benchmarks is represented as:

```
leveldb_put_seq_sync/(1, 100)
                        time:   [57.474 us 58.370 us 59.578 us]
```

And in [this example HTML report](https://mykmelez.github.io/kvbench/criterion/report/), it looks like this:

* lmdb_put_seq_sync
  * (1, 100)

Although I've explained the numbers elsewhere (in code comments and the project's README), it'd be helpful to provide this information contextually, in representations of the benchmarks, both in the command line output and in the HTML report.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

You can already do this. The reason the parameter type (in this case, the type `(i32, i32)`) must implement Debug is because that is how the values are converted to Strings for display. If you'd like to customize this conversion, you can create your own parameter struct to use instead of a tuple, and either `#[derive(Debug)]` or implement the Debug trait manually.

Hope this helps!
