### ISSUE TITLE
Enable dependabot for criterion

### ISSUE THREAD

**Issue by gnzlbg** [japaric/criterion.rs#207]
Dependabot can be set up to end PRs monthly which update dependencies to their latest version.

**Comment by bheisler** [comment]
Thanks for the suggestion!

After thinking about it, I'm not sure this makes sense. I always manually update the dependencies before releasing a new version anyway (and this can be a non-trivial process, since I have to support Rust 1.23.0 and 1.20.0, and voluntarily support `-Z minimal-versions`). Updating dependencies in the repository doesn't affect much without a release.

**Comment by gnzlbg** [comment]
I feel the pain. I don't think there is a good solution to this problem. For example, if someone is using "nightly", then they are often using the latest dependencies, and compiling criterion will require downloading and compiling older versions of the same dependencies. The way to improve this for nightly users is to keep the dependencies up-to-date, but this breaks people using older Rust versions =/
